### ISSUE TITLE
missing cmake module file: CMake-downloadInformation.cmake

### ISSUE THREAD

**Issue by ShahOdin** [Crascit/DownloadProject#22]
I used to be able to get this working on Linux and Windows. Not sure about the cmake version numbers.

Now however, with Cmake 3.6.0-rc2 on Windows and with Cmake 3.5.1 on Ubuntu, I am getting: 

**CMake Error: Could not find cmake module file: CMake-downloadInformation.cmake**

-- Configuring incomplete, errors occurred!

CMake Error at cmake/modules/DownloadProject.cmake:167 (message):
  CMake step for googletest failed: 1
Call Stack (most recent call first):
  cmake/modules/custom_DownloadProject.cmake:83 (download_project)
  cmake/ExternalLists.cmake:5 (custom_AddDownloadProject)
  CMakeLists.txt:20 (include)

Is this an official Cmake module that no longer exists?

**Comment by audiofanatic** [comment]
You haven't provided enough information to be able to offer advice on the problem. What are you trying to download? Have you modified DownloadProject.cmake or DownloadProject.CMakeLists.cmake.in? Can you provide the full set of files to reproduce the problem?

Also try completely removing your build directory and build from scratch to see if that makes the problem go away. 

I'm not aware of anything changing in CMake which would lead to symptoms like those you've described.

**Comment by audiofanatic** [comment]
No response for a month, closing.
