### ISSUE TITLE
Can't build MariaDB C connector

### ISSUE THREAD

**Issue by ruipacheco** [Crascit/DownloadProject#25]
I'm using this to build the C connector for [MariaDB](https://github.com/MariaDB/mariadb-connector-c) but the process never goes beyond the download stage.

I have this on my CMakeLists.txt:

```
download_project(PROJ               mariadb-connector-c
                 GIT_REPOSITORY     https://github.com/MariaDB/mariadb-connector-c
                 GIT_TAG            v_2.3.3
                 ${UPDATE_DISCONNECTED_IF_AVAILABLE}
)
```

and I can see that source files are downloaded correctly. It just doesn't build them and no errors are shown.

I use this with Catch, a header only library, without any problems:

```
download_project(PROJ               catch
                 GIT_REPOSITORY     https://github.com/philsquared/Catch
                 GIT_TAG            v1.9.4
                 ${UPDATE_DISCONNECTED_IF_AVAILABLE}
)
include_directories(${catch_SOURCE_DIR}/single_include/)
```

**Comment by craigscott-crascit** [comment]
The `include_directories()` command merely adds the listed directories to the header search path, which is probably what you intended for `catch`. For `mariadb-connector-c`, did you put an `add_subdirectory()` after the `download_project()` command? Without that, there's nothing pulling in the build after it is downloaded. See the [example](https://github.com/Crascit/DownloadProject/blob/master/CMakeLists.txt#L24) in the DownloadProject repo which uses `add_subdirectory()` after the download.

**Comment by ruipacheco** [comment]
Perfect, thanks.
