### ISSUE TITLE
How can we disable the install step?

### ISSUE THREAD

**Issue by gabyx** [Crascit/DownloadProject#3]
When I used your extension as

```
include(DownloadProject)
download_project(PROJ                googletest
                 GIT_REPOSITORY      https://github.com/google/googletest.git
                 GIT_TAG             master
                 ${UPDATE_DISCONNECTED_IF_AVAILABLE}
)
add_subdirectory(${googletest_SOURCE_DIR} ${googletest_BINARY_DIR})
```

I have the problem that the downloaded project gets installed as well when my project installs
can I somehow disable this?

This is not related to this library but maybe you can help :-)

**Comment by audiofanatic** [comment]
That will be controlled by whatever googletest does in its own CMakeLists.txt file. I suggest you ask on the GoogleTest group:

https://groups.google.com/forum/#!forum/googletestframework

**Comment by gabyx** [comment]
Got the solution by adding EXCLUDE_FROM_ALL
in the add_subdirectory command

that will not install the stuff :)

**Comment by audiofanatic** [comment]
Just note that EXCLUDE_FROM_ALL doesn't work with the Xcode generator. See the following link for details:

https://public.kitware.com/Bug/view.php?id=8365

**Comment by gabyx** [comment]
Ahh thanks!

hm… what would then be a way of not installing the whole stuff, when I used gtest in may framework, :-)

have no idea 
https://github.com/gabyx/ApproxMVBB <https://github.com/gabyx/ApproxMVBB>


probably , delete again all installed stuff (stupid but no other choice )

**Comment by audiofanatic** [comment]
There may be a way to control what gets installed. Perhaps ask on the CMake Users mailing list:

https://cmake.org/mailing-lists/

That should draw on a deeper pool of knowledge which may offer some alternatives for you.

**Comment by gabyx** [comment]
thanks for the help anyway!

=)
